#!/bin/bash
#
# Copyright (c) 2016 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

while [ $# -gt 0 ]; do
  case "$1" in
    --org=*)
      org="${1#*=}"
      ;;
    --dir=*)
      dir="${1#*=}"
      ;;
    --domain=*)
      domain="${1#*=}"
      ;;
    --port=*)
      port="${1#*=}"
      ;;
    *)
      printf "Error: Invalid argument.\n"
      exit 1
  esac
  shift
done

if [[ -f "$dir" ]]
then
  printf "Error: The path parameter specifies a file path, not a directory path.\n"
  exit 1
fi

dir_files=(` ls $dir -p | grep -v / `)

files=""
for ((i=0;i<${#dir_files[@]} ;i++)); do
    files+="-F upload=@$dir/${dir_files[i]} "
done

if [ "$domain" != "" ]; then
	curl -H "Authorization: `cf oauth-token | grep bearer`" -v -F orgUUID=`cf org $org --guid` -F category=business -F title=upload-data $files http://hdfs-uploader.$domain/rest/v1/files/`cf org $org --guid`;
else
    if [ "$port" != "" ]; then
	    curl -H "Authorization: `cf oauth-token | grep bearer`" -v -F orgUUID=`cf org $org --guid` -F category=business -F title=upload-data $files http://localhost:$port/rest/v1/files/`cf org $org --guid`;
	else
	    curl -H "Authorization: `cf oauth-token | grep bearer`" -v -F orgUUID=`cf org $org --guid` -F category=business -F title=upload-data $files http://localhost:8080/rest/v1/files/`cf org $org --guid`;
	fi
fi
